"""Per-clinic inbound webhook configuration."""

import uuid
from datetime import datetime, timezone

from sqlalchemy import Boolean, Column, DateTime, Integer, String

from app.db.base import Base


class ClinicWebhookConfig(Base):
    __tablename__ = "clinic_webhook_configs"

    id = Column(String, primary_key=True, default=lambda: f"WHK-{uuid.uuid4().hex[:10].upper()}")
    clinic_id = Column(String, nullable=False, index=True)

    label = Column(String, nullable=False)  # e.g. "WooCommerce Production"
    # Payload format the sender uses.  NeuroFlow normalises all of these into
    # the same internal representation before running the intake pipeline.
    # Supported: woocommerce | stripe | cliniko | acuity | generic
    payload_format = Column(String, nullable=False, default="generic")

    # HMAC-SHA256 signing secret.  Stored in plaintext here (it is not a
    # user credential — it is a server-to-server shared secret generated by
    # NeuroFlow and given to the clinic's platform).
    signing_secret = Column(String, nullable=False)

    active = Column(Boolean, default=True, nullable=False)

    # Counters for the dashboard
    events_received = Column(Integer, default=0, nullable=False)
    last_event_at = Column(DateTime, nullable=True)

    created_at = Column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc))
